// 365 Daily Motivational Quotes for GRE with Nanda
// Index 0-364, selected by day-of-year
const DAILY_QUOTES = [
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "The beautiful thing about learning is that nobody can take it away from you.", author: "B.B. King" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Learning is not attained by chance, it must be sought for with ardor and attended to with diligence.", author: "Abigail Adams" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { text: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Knowledge is power. Information is liberating.", author: "Kofi Annan" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "What we learn with pleasure we never forget.", author: "Alfred Mercier" },
  { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Don't count the days; make the days count.", author: "Muhammad Ali" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Arnold Schwarzenegger" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "Your education is a dress rehearsal for a life that is yours to lead.", author: "Nora Ephron" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "With self-discipline most anything is possible.", author: "Theodore Roosevelt" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { text: "Every word you learn is a door you can open.", author: "Nanda's GRE Journey" },
  { text: "The beginning is always today.", author: "Mary Shelley" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
  { text: "A little progress each day adds up to big results.", author: "Satya Nani" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "Be not afraid of going slowly; be afraid only of standing still.", author: "Chinese Proverb" },
  { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Your vocabulary is your intellectual wardrobe. Dress well.", author: "Nanda's GRE Journey" },
  { text: "Today a reader, tomorrow a leader.", author: "Margaret Fuller" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "The only way to learn mathematics is to do mathematics.", author: "Paul Halmos" },
  { text: "Words are the dress of thoughts.", author: "Samuel Johnson" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { text: "Every new word is a new tool for thinking.", author: "Nanda's GRE Journey" },
  { text: "Patience, persistence, and perspiration make an unbeatable combination for success.", author: "Napoleon Hill" },
  { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
  { text: "Nothing is impossible. The word itself says I'm possible.", author: "Audrey Hepburn" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "The only source of knowledge is experience.", author: "Albert Einstein" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "The pen is mightier than the sword.", author: "Edward Bulwer-Lytton" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { text: "To know that we know what we know, and that we do not know what we do not know, that is true knowledge.", author: "Nicolaus Copernicus" },
  { text: "By three methods we may learn wisdom: First, by reflection, which is noblest; second, by imitation, which is easiest; and third by experience, which is the bitterest.", author: "Confucius" },
  { text: "The mind once stretched by a new idea never returns to its original dimensions.", author: "Oliver Wendell Holmes" },
  { text: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein" },
  { text: "One word at a time, you're building a new you.", author: "Nanda's GRE Journey" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "I am still learning.", author: "Michelangelo" },
  { text: "You can never be overdressed or overeducated.", author: "Oscar Wilde" },
  { text: "The world is a book and those who do not travel read only one page.", author: "Saint Augustine" },
  { text: "There is no friend as loyal as a book.", author: "Ernest Hemingway" },
  { text: "The greatest teacher, failure is.", author: "Yoda" },
  { text: "Study without desire spoils the memory, and it retains nothing that it takes in.", author: "Leonardo da Vinci" },
  { text: "To have another language is to possess a second soul.", author: "Charlemagne" },
  { text: "Words have the power to both destroy and heal. When words are both true and kind, they can change our world.", author: "Buddha" },
  { text: "The limits of my language mean the limits of my world.", author: "Ludwig Wittgenstein" },
  { text: "If you talk to a man in a language he understands, that goes to his head. If you talk to him in his language, that goes to his heart.", author: "Nelson Mandela" },
  { text: "Language is the road map of a culture.", author: "Rita Mae Brown" },
  { text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison" },
  { text: "The only person who is educated is the one who has learned how to learn and change.", author: "Carl Rogers" },
  { text: "Preparation is the key to success.", author: "Alexander Graham Bell" },
  { text: "You don't have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
  { text: "Every master was once a disaster.", author: "T. Harv Eker" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "The more I read, the more I acquire, the more certain I am that I know nothing.", author: "Voltaire" },
  { text: "Today's preparation determines tomorrow's achievement.", author: "Unknown" },
  { text: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", author: "Jordan Belfort" },
  { text: "You're one vocabulary session closer to your dream school.", author: "Nanda's GRE Journey" },
  { text: "Learning another language is not only learning different words for the same things, but learning another way to think about things.", author: "Flora Lewis" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "The more you know, the more you realize you don't know.", author: "Aristotle" },
  { text: "Education costs money. But then so does ignorance.", author: "Claus Moser" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { text: "Not all readers are leaders, but all leaders are readers.", author: "Harry S. Truman" },
  { text: "Once you learn to read, you will be forever free.", author: "Frederick Douglass" },
  { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { text: "Think before you speak. Read before you think.", author: "Fran Lebowitz" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "Education is not filling a pail, but the lighting of a fire.", author: "William Butler Yeats" },
  { text: "What we know is a drop, what we don't know is an ocean.", author: "Isaac Newton" },
  { text: "Intelligence plus character — that is the goal of true education.", author: "Martin Luther King Jr." },
  { text: "Develop a passion for learning. If you do, you will never cease to grow.", author: "Anthony J. D'Angelo" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { text: "When you know better, you do better.", author: "Maya Angelou" },
  { text: "Mastering GRE words is just the beginning of mastering your future.", author: "Nanda's GRE Journey" },
  { text: "The function of education is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr." },
  { text: "Anyone who stops learning is old, whether at twenty or eighty.", author: "Henry Ford" },
  { text: "To teach is to learn twice.", author: "Joseph Joubert" },
  { text: "Have no fear of perfection — you'll never reach it.", author: "Salvador Dalí" },
  { text: "In learning you will teach, and in teaching you will learn.", author: "Phil Collins" },
  { text: "Curiosity is the wick in the candle of learning.", author: "William Arthur Ward" },
  { text: "Self-education is, I firmly believe, the only kind of education there is.", author: "Isaac Asimov" },
  { text: "All things are difficult before they are easy.", author: "Thomas Fuller" },
  { text: "If people did not do silly things, nothing intelligent would ever get done.", author: "Ludwig Wittgenstein" },
  { text: "The noblest pleasure is the joy of understanding.", author: "Leonardo da Vinci" },
  { text: "What seems to us as bitter trials are often blessings in disguise.", author: "Oscar Wilde" },
  { text: "If we encounter a man of rare intellect, we should ask him what books he reads.", author: "Ralph Waldo Emerson" },
  { text: "Intellectual growth should commence at birth and cease only at death.", author: "Albert Einstein" },
  { text: "Every day is a chance to learn something new.", author: "Nanda's GRE Journey" },
  { text: "I cannot teach anybody anything. I can only make them think.", author: "Socrates" },
  { text: "Reading furnishes the mind only with materials of knowledge; it is thinking that makes what we read ours.", author: "John Locke" },
  { text: "Wonder is the beginning of wisdom.", author: "Socrates" },
  { text: "No thief, however skillful, can rob one of knowledge, and that is why knowledge is the best and safest treasure to acquire.", author: "L. Frank Baum" },
  { text: "The only thing worse than being blind is having sight but no vision.", author: "Helen Keller" },
  { text: "Life is a succession of lessons which must be lived to be understood.", author: "Helen Keller" },
  { text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
  { text: "The wise man does at once what the fool does finally.", author: "Niccolò Machiavelli" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
  { text: "Not everything that is faced can be changed, but nothing can be changed until it is faced.", author: "James Baldwin" },
  { text: "The secret to getting ahead is getting started.", author: "Agatha Christie" },
  { text: "Every word you master is a weapon in your GRE arsenal.", author: "Nanda's GRE Journey" },
  { text: "Happiness is not something readymade. It comes from your own actions.", author: "Dalai Lama" },
  { text: "The purpose of learning is growth, and our minds, unlike our bodies, can continue growing as we continue to live.", author: "Mortimer Adler" },
  { text: "Just one small positive thought in the morning can change your whole day.", author: "Dalai Lama" },
  { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
  { text: "The mind that opens to a new idea never returns to its original size.", author: "Albert Einstein" },
  { text: "Difficult roads often lead to beautiful destinations.", author: "Zig Ziglar" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Your GRE score is just the beginning of your next chapter.", author: "Nanda's GRE Journey" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine" },
  { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller Jr." },
  { text: "I think, therefore I am.", author: "René Descartes" },
  { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { text: "Go confidently in the direction of your dreams.", author: "Henry David Thoreau" },
  { text: "The soul that is within me no man can degrade.", author: "Frederick Douglass" },
  { text: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", author: "James Cameron" },
  { text: "The whole purpose of education is to turn mirrors into windows.", author: "Sydney J. Harris" },
  { text: "A word fitly spoken is like apples of gold in a setting of silver.", author: "Proverbs 25:11" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "You're doing something amazing. Don't stop now.", author: "Nanda's GRE Journey" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
  { text: "Only those who dare to fail greatly can ever achieve greatly.", author: "Robert F. Kennedy" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "I have no special talents. I am only passionately curious.", author: "Albert Einstein" },
  { text: "The only way to learn is by doing.", author: "Plato" },
  { text: "He who is not a good servant will not be a good master.", author: "Plato" },
  { text: "Out of clutter, find simplicity.", author: "Albert Einstein" },
  { text: "Vocabulary isn't just words — it's the architecture of thought.", author: "Nanda's GRE Journey" },
  { text: "Those who know nothing of foreign languages know nothing of their own.", author: "Johann Wolfgang von Goethe" },
  { text: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", author: "Ernest Hemingway" },
  { text: "May you live all the days of your life.", author: "Jonathan Swift" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin" },
  { text: "The only real failure is the failure to try.", author: "Unknown" },
  { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "Strength and growth come only through continuous effort and struggle.", author: "Napoleon Hill" },
  { text: "Every flashcard you flip brings you closer to your goal.", author: "Nanda's GRE Journey" },
  { text: "Your present circumstances don't determine where you can go; they merely determine where you start.", author: "Nido Qubein" },
  { text: "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.", author: "Earl Nightingale" },
  { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { text: "Wisdom begins in wonder.", author: "Socrates" },
  { text: "In the realm of ideas everything depends on enthusiasm; in the real world all rests on perseverance.", author: "Johann Wolfgang von Goethe" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "Let us remember: One book, one pen, one child, and one teacher can change the world.", author: "Malala Yousafzai" },
  { text: "A reader lives a thousand lives before he dies.", author: "George R.R. Martin" },
  { text: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix" },
  { text: "The art of teaching is the art of assisting discovery.", author: "Mark Van Doren" },
  { text: "Without struggle, there is no progress.", author: "Frederick Douglass" },
  { text: "Every day you study is a vote for the person you want to become.", author: "Nanda's GRE Journey" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { text: "The important thing is to never stop questioning.", author: "Albert Einstein" },
  { text: "It is not enough to have a good mind; the main thing is to use it well.", author: "René Descartes" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "A thousand-mile journey begins beneath one's feet.", author: "Lao Tzu" },
  { text: "Hope is not the conviction that something will turn out well, but the certainty that something makes sense, regardless of how it turns out.", author: "Václav Havel" },
  { text: "The wise adapt themselves to circumstances, as water molds itself to the pitcher.", author: "Chinese Proverb" },
  { text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
  { text: "Words are, in my not-so-humble opinion, our most inexhaustible source of magic.", author: "J.K. Rowling" },
  { text: "You are enough. You have enough. You do enough.", author: "Nanda's GRE Journey" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "Where there is a will, there is a way.", author: "English Proverb" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
  { text: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr." },
  { text: "To read is to fly: it is to soar to a point of vantage which gives a view over wide terrains of history, human variety, ideas, shared experience and the fruits of many inquiries.", author: "A.C. Grayling" },
  { text: "Today is a good day to learn a new word.", author: "Nanda's GRE Journey" },
  { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "The price of anything is the amount of life you exchange for it.", author: "Henry David Thoreau" },
  { text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
  { text: "What is now proved was once only imagined.", author: "William Blake" },
  { text: "Some people dream of success, while other people get up every morning and make it happen.", author: "Wayne Huizenga" },
  { text: "The energy of the mind is the essence of life.", author: "Aristotle" },
  { text: "One language sets you in a corridor for life. Two languages open every door along the way.", author: "Frank Smith" },
  { text: "Nothing worth having comes easy.", author: "Theodore Roosevelt" },
  { text: "Rest, but never quit.", author: "Nanda's GRE Journey" },
  { text: "What counts in life is not the mere fact that we have lived.", author: "Nelson Mandela" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Plato" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself.", author: "Marcus Aurelius" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good person should be. Be one.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "One must still have chaos in oneself to give birth to a dancing star.", author: "Friedrich Nietzsche" },
  { text: "Knowing words is knowing the world.", author: "Nanda's GRE Journey" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "The wound is the place where the Light enters you.", author: "Rumi" },
  { text: "Let yourself be silently drawn by the strange pull of what you really love.", author: "Rumi" },
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
  { text: "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.", author: "Rumi" },
  { text: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", author: "Rumi" },
  { text: "The garden of the world has no limits, except in your mind.", author: "Rumi" },
  { text: "Respond to every call that excites your spirit.", author: "Rumi" },
  { text: "When the world pushes you to your knees, you're in the perfect position to pray.", author: "Rumi" },
  { text: "Every morning brings new potential, but if you dwell on the misfortunes of the day before, you tend to overlook tremendous opportunities.", author: "Harvey Mackay" },
  { text: "Today's vocabulary word might just appear on your GRE. Keep going.", author: "Nanda's GRE Journey" },
  { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "Health is the greatest possession. Contentment is the greatest treasure.", author: "Lao Tzu" },
  { text: "He who conquers himself is the mightiest warrior.", author: "Confucius" },
  { text: "Study the past, if you would define the future.", author: "Confucius" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
  { text: "It is not the mountain we conquer but ourselves.", author: "Edmund Hillary" },
  { text: "Where there is no struggle, there is no strength.", author: "Oprah Winfrey" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "Every session counts, even the short ones.", author: "Nanda's GRE Journey" },
  { text: "This too shall pass.", author: "Persian Proverb" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { text: "The Earth has music for those who listen.", author: "William Shakespeare" },
  { text: "Though she be but little, she is fierce.", author: "William Shakespeare" },
  { text: "All that we are is the result of what we have thought.", author: "Buddha" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "There is no path to happiness: happiness is the path.", author: "Buddha" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
  { text: "Every morning we are born again. What we do today matters most.", author: "Buddha" },
  { text: "Your progress is invisible to you because you see it every day. But it's real.", author: "Nanda's GRE Journey" },
  { text: "I dwell in possibility.", author: "Emily Dickinson" },
  { text: "Hope is the thing with feathers that perches in the soul.", author: "Emily Dickinson" },
  { text: "Forever is composed of nows.", author: "Emily Dickinson" },
  { text: "Not knowing when the dawn will come, I open every door.", author: "Emily Dickinson" },
  { text: "We do not need magic to transform our world. We carry all the power we need inside ourselves already.", author: "J.K. Rowling" },
  { text: "Imagination is the beginning of creation.", author: "George Bernard Shaw" },
  { text: "Those who mind don't matter, and those who matter don't mind.", author: "Bernard Baruch" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.", author: "Vincent Van Gogh" },
  { text: "I have learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "Nanda, you've got this. One word, one question, one day at a time.", author: "Your GRE Journey" },
  { text: "Courage is not the absence of fear, but rather the assessment that something else is more important than fear.", author: "Franklin D. Roosevelt" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "Alone we can do so little; together we can do so much.", author: "Helen Keller" },
  { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
  { text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker" },
  { text: "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.", author: "Eleanor Roosevelt" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "You're smarter than you think, Nanda. The GRE can't measure your full potential.", author: "Your GRE Journey" },
  { text: "When we strive to become better than we are, everything around us becomes better too.", author: "Paulo Coelho" },
  { text: "And, when you want something, all the universe conspires in helping you to achieve it.", author: "Paulo Coelho" },
  { text: "The simple things are also the most extraordinary things, and only the wise can see them.", author: "Paulo Coelho" },
  { text: "One day or day one. You decide.", author: "Unknown" },
  { text: "Every expert was once a beginner. Every pro was once an amateur.", author: "Unknown" },
  { text: "Wake up determined. Go to bed satisfied.", author: "Dwayne Johnson" },
  { text: "It is in your moments of decision that your destiny is shaped.", author: "Tony Robbins" },
  { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
  { text: "The only limit to the height of your achievements is the reach of your dreams.", author: "Michelle Obama" },
  { text: "For there is always light, if only we're brave enough to see it. If only we're brave enough to be it.", author: "Amanda Gorman" },
  { text: "Mastery is not about being perfect. It's about being persistent.", author: "Nanda's GRE Journey" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "A mind that is stretched by a new experience can never go back to its old dimensions.", author: "Oliver Wendell Holmes Jr." },
  { text: "The way I see it, if you want the rainbow, you gotta put up with the rain.", author: "Dolly Parton" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { text: "Two roads diverged in a wood, and I — I took the one less traveled by.", author: "Robert Frost" },
  { text: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss" },
  { text: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },
  { text: "Why fit in when you were born to stand out?", author: "Dr. Seuss" },
  { text: "Unless someone like you cares a whole awful lot, nothing is going to get better. It's not.", author: "Dr. Seuss" },
  { text: "A champion is defined not by their wins but by how they can recover when they fall.", author: "Serena Williams" },
  { text: "The day you plant the seed is not the day you eat the fruit.", author: "Fabienne Fredrickson" },
  { text: "Every word learned is a seed planted. Your garden is growing, Nanda.", author: "Your GRE Journey" },
  { text: "She believed she could, so she did.", author: "R.S. Grey" },
  { text: "A woman with a voice is, by definition, a strong woman.", author: "Melinda Gates" },
  { text: "I raise up my voice — not so I can shout, but so that those without a voice can be heard.", author: "Malala Yousafzai" },
  { text: "There is no force more powerful than a woman determined to rise.", author: "W.E.B. Du Bois" },
  { text: "I am my best work — a series of road maps, reports, recipes, doodles, and prayers from the front lines.", author: "Audre Lorde" },
  { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
  { text: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", author: "Maya Angelou" },
  { text: "I am not free while any woman is unfree, even when her shackles are very different from my own.", author: "Audre Lorde" },
  { text: "My mission in life is not merely to survive, but to thrive.", author: "Maya Angelou" },
  { text: "No one is born hating another person. People must learn to hate, and if they can learn to hate, they can be taught to love.", author: "Nelson Mandela" },
  { text: "GRE day will come and go. The discipline you're building lasts forever.", author: "Nanda's GRE Journey" },
  { text: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.", author: "Maya Angelou" },
  { text: "You are the sum total of everything you've ever seen, heard, eaten, smelled, been told, forgot.", author: "Maya Angelou" },
  { text: "Still I rise.", author: "Maya Angelou" },
  { text: "Education breeds confidence. Confidence breeds hope. Hope breeds peace.", author: "Confucius" },
  { text: "Time you enjoy wasting is not wasted time.", author: "Marthe Troly-Curtin" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
  { text: "The greatest discovery of all time is that a person can change their future by merely changing their attitude.", author: "Oprah Winfrey" },
  { text: "Think like a queen. A queen is not afraid to fail.", author: "Oprah Winfrey" },
  { text: "Surround yourself with only people who are going to lift you higher.", author: "Oprah Winfrey" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "Learning a new word is like meeting a new friend — awkward at first, then indispensable.", author: "Nanda's GRE Journey" },
  { text: "The greatest wealth is to live content with little.", author: "Plato" },
  { text: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato" },
  { text: "Good actions give strength to ourselves and inspire good actions in others.", author: "Plato" },
  { text: "Music gives a soul to the universe, wings to the mind, flight to the imagination, and life to everything.", author: "Plato" },
  { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare" },
  { text: "There are more things in Heaven and Earth than are dreamt of in your philosophy.", author: "William Shakespeare" },
  { text: "The world is full of magical things patiently waiting for our wits to grow sharper.", author: "Bertrand Russell" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Educating the mind without educating the heart is no education at all.", author: "Aristotle" },
  { text: "Knowing what you know today, you'd still choose this path. Trust yourself.", author: "Nanda's GRE Journey" },
  { text: "The only person you should try to be better than is the person you were yesterday.", author: "Unknown" },
  { text: "Don't compare your beginning to someone else's middle.", author: "Jon Acuff" },
  { text: "You will never always be motivated, so you must learn to be disciplined.", author: "Unknown" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
  { text: "I did then what I knew how to do. Now that I know better, I do better.", author: "Maya Angelou" },
  { text: "At the end of the day, you can either focus on what's tearing you apart or what's holding you together.", author: "Unknown" },
  { text: "She remembered who she was and the game changed.", author: "Lalah Delia" },
  { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Here's to the crazy ones. The misfits. The rebels. The troublemakers.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Your work is going to fill a large part of your life. Don't settle.", author: "Nanda's GRE Journey" },
  { text: "Be curious, not judgmental.", author: "Walt Whitman" },
  { text: "I contain multitudes.", author: "Walt Whitman" },
  { text: "Every atom belonging to me as good belongs to you.", author: "Walt Whitman" },
  { text: "Keep your face always toward the sunshine — and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "To know even one life has breathed easier because you have lived, this is to have succeeded.", author: "Ralph Waldo Emerson" },
  { text: "What we think, we become.", author: "Margaret Thatcher" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain" },
  { text: "Courage is resistance to fear, mastery of fear — not absence of fear.", author: "Mark Twain" }
];
