// Reading Comprehension Questions — GRE-style
// Format: passage + 2-4 questions, each with 5 choices
const RC_DATA = [
  {id:"rc1",passage:"The conventional understanding of the Industrial Revolution as a period of unqualified progress has been increasingly challenged by historians who emphasize its devastating social costs. While factories produced unprecedented quantities of goods, they also created a new class of urban poor who lived in squalid conditions and worked grueling hours for meager wages. Children as young as five labored in mines and mills, and life expectancy in industrial cities actually declined during the early stages of industrialization. Revisionist historians argue that the benefits of industrialization were distributed so unevenly that it is misleading to characterize the period simply as one of advancement.",questions:[
    {question:"The passage primarily serves to",choices:["celebrate the achievements of the Industrial Revolution","argue that industrialization was entirely harmful","present a more nuanced view of a historical period","propose specific reforms to address industrial-era problems","compare different countries' experiences with industrialization"],correct:2,explanation:"The passage challenges the 'conventional understanding' of pure progress by presenting social costs alongside economic gains. It offers a more complex, nuanced picture — not entirely negative (option B), but not purely positive either."},
    {question:"The author mentions children working in mines primarily to",choices:["advocate for child labor laws","provide specific evidence of industrialization's human costs","compare modern and historical labor practices","criticize factory owners for their greed","argue that children were more productive than adults"],correct:1,explanation:"The detail about child laborers serves as concrete evidence supporting the passage's argument that industrialization had 'devastating social costs.' It's one of several examples illustrating the human toll."},
    {question:"Based on the passage, 'revisionist historians' would most likely agree that",choices:["the Industrial Revolution produced no meaningful benefits","economic growth alone is an insufficient measure of progress","factory conditions were acceptable for their time","industrialization benefited all social classes equally","traditional histories of industrialization are completely fabricated"],correct:1,explanation:"Revisionist historians argue that benefits were 'distributed so unevenly' that calling the period simply 'advancement' is 'misleading.' This implies they believe progress should be measured by who benefits, not just total output — economic growth alone is insufficient."}
  ],difficulty:1,tags:["history","social"]},

  {id:"rc2",passage:"Recent research in behavioral economics has revealed that human decision-making frequently deviates from the rational actor model that has long dominated economic theory. Studies have shown that individuals routinely make choices that are inconsistent, influenced by irrelevant information, and contrary to their own stated preferences. For example, people tend to weigh potential losses more heavily than equivalent potential gains — a phenomenon known as loss aversion. They are also susceptible to framing effects, making different choices depending on how options are presented, even when the underlying outcomes are identical. These findings have profound implications for public policy, suggesting that the design of choices can significantly influence behavior without restricting freedom of action.",questions:[
    {question:"The passage suggests that loss aversion would most likely cause an investor to",choices:["sell a profitable stock to realize gains","hold onto a losing stock rather than accept the loss","diversify their portfolio across multiple sectors","invest more heavily in high-risk ventures","ignore market fluctuations entirely"],correct:1,explanation:"Loss aversion means people 'weigh potential losses more heavily than equivalent gains.' An investor would therefore be reluctant to sell a losing stock because doing so would mean accepting (realizing) a loss, which feels more painful than the equivalent gain feels good."},
    {question:"The phrase 'framing effects' as used in the passage most nearly refers to",choices:["the physical presentation of economic data in charts","how the way options are described influences decisions","the framework economists use to analyze behavior","the limitations of laboratory experiments","the effect of media coverage on public opinion"],correct:1,explanation:"The passage defines framing effects through the example: 'making different choices depending on how options are presented, even when the underlying outcomes are identical.' It's about how the description/presentation of choices affects decisions."},
    {question:"The author's attitude toward traditional economic theory can best be described as",choices:["dismissive and contemptuous","respectful but critical","wholly supportive","indifferent and detached","hostile and accusatory"],correct:1,explanation:"The author presents traditional theory ('rational actor model') neutrally as having 'long dominated' the field, showing respect for its importance. But the passage then shows how reality 'deviates' from this model — a critical but not hostile stance."}
  ],difficulty:1,tags:["economics","psychology"]},

  {id:"rc3",passage:"The relationship between biodiversity and ecosystem stability has been the subject of considerable scientific debate. The diversity-stability hypothesis proposes that ecosystems with greater species diversity are more resistant to disruption and recover more quickly from disturbances. Proponents point to evidence that diverse grasslands, for instance, maintain more consistent productivity during droughts than monocultures. However, critics note that the relationship may be more complex than a simple positive correlation suggests. Some studies have found that in certain ecosystems, a few dominant species contribute disproportionately to ecosystem function, and that adding species beyond a certain threshold produces diminishing returns in terms of stability. The emerging consensus is that while biodiversity generally promotes stability, the specific mechanisms vary significantly across different ecosystems.",questions:[
    {question:"Which of the following best describes the structure of the passage?",choices:["A hypothesis is presented, evidence is given, and the hypothesis is rejected","Two competing theories are compared, and one is declared superior","A theory is introduced, complications are noted, and a nuanced conclusion is reached","A historical overview leads to a prediction about future research","An experiment is described, its flaws are identified, and an alternative is proposed"],correct:2,explanation:"The passage introduces the diversity-stability hypothesis, presents supporting evidence, then notes critics' complications, and concludes with a nuanced consensus. This matches option C perfectly."},
    {question:"The example of diverse grasslands during droughts serves to",choices:["disprove the critics' objections","illustrate the diversity-stability hypothesis","demonstrate that monocultures are always inferior","prove that all ecosystems follow the same pattern","introduce a new area of research"],correct:1,explanation:"The grassland example is introduced immediately after the diversity-stability hypothesis as evidence that diverse systems are 'more resistant to disruption' — it directly illustrates the hypothesis."},
    {question:"The passage suggests that the relationship between biodiversity and stability is",choices:["nonexistent and merely a correlation","universally positive across all ecosystems","generally positive but context-dependent","entirely determined by dominant species","too complex to study scientifically"],correct:2,explanation:"The 'emerging consensus' states that biodiversity 'generally promotes stability' (positive) but 'specific mechanisms vary significantly across different ecosystems' (context-dependent). This matches option C."}
  ],difficulty:2,tags:["science","ecology"]},

  {id:"rc4",passage:"Critics of contemporary art often complain that modern works lack the technical skill evident in classical paintings and sculptures. This critique, while understandable, fundamentally mischaracterizes the aims of much contemporary art. The shift away from technical virtuosity was not a consequence of declining skill but a deliberate philosophical choice. Artists like Marcel Duchamp argued that art's value lies not in the physical execution but in the intellectual concept behind the work. By presenting a mass-produced urinal as sculpture, Duchamp challenged the very definition of art and questioned the privileged status of the handmade object. Whether one finds this liberating or exasperating, it represents a coherent philosophical position rather than mere incompetence.",questions:[
    {question:"The author's primary purpose is to",choices:["argue that contemporary art is superior to classical art","defend contemporary art against a common misconception","describe the technical methods used in modern art","provide a biography of Marcel Duchamp","criticize the commercial art market"],correct:1,explanation:"The author directly addresses the 'common complaint' that modern art lacks skill and argues this criticism 'fundamentally mischaracterizes' contemporary art's aims. The purpose is to correct this misunderstanding."},
    {question:"The author mentions Duchamp's urinal primarily to",choices:["shock the reader with an unusual example","provide evidence that contemporary art requires no skill","illustrate how art can prioritize concept over technique","argue that everyday objects are inherently artistic","criticize Duchamp's contribution to art history"],correct:2,explanation:"Duchamp's urinal exemplifies the passage's central argument: that some artists deliberately chose to emphasize intellectual concepts over physical execution. The urinal is the concrete example of prioritizing concept over technique."}
  ],difficulty:1,tags:["art","philosophy"]},

  {id:"rc5",passage:"The widespread adoption of remote work during the pandemic accelerated trends that had been slowly developing for decades. However, the benefits of remote work have not been distributed equally. Knowledge workers in fields like technology and finance found that productivity often increased when freed from commuting and office distractions. But workers in lower-wage sectors — retail, food service, manufacturing — largely could not perform their jobs remotely and continued to face in-person health risks. Even among remote-eligible workers, disparities emerged: employees with dedicated home offices, reliable internet, and no childcare responsibilities fared far better than those working from kitchen tables while supervising children's online schooling. The remote work revolution, for all its promise, has thus widened existing socioeconomic divides rather than narrowing them.",questions:[
    {question:"The author's central argument is that remote work",choices:["is universally beneficial for workers","has increased productivity across all sectors","has exacerbated inequality between different groups","should be permanently adopted by all companies","is a temporary trend that will soon reverse"],correct:2,explanation:"The passage's thesis appears in the final sentence: remote work 'has widened existing socioeconomic divides rather than narrowing them.' The entire passage builds evidence showing how benefits were unequally distributed."},
    {question:"The author mentions 'kitchen tables' most likely to",choices:["suggest that all remote workers are uncomfortable","provide a vivid contrast with dedicated home offices","criticize companies for not providing equipment","argue that remote work is fundamentally flawed","recommend that workers invest in better furniture"],correct:1,explanation:"The 'kitchen table' image is contrasted with 'dedicated home offices' to illustrate the disparity among remote workers themselves. It's a concrete, vivid detail that makes the inequality tangible."},
    {question:"Based on the passage, which worker would LEAST benefit from remote work?",choices:["A software engineer with a home office","A financial analyst with fast internet","A retail cashier at a grocery store","A marketing manager living alone","A data scientist with no children"],correct:2,explanation:"The passage explicitly states that workers in 'retail, food service, manufacturing' could not work remotely and faced in-person health risks. A retail cashier cannot do their job from home at all."}
  ],difficulty:1,tags:["society","economics"]},

  {id:"rc6",passage:"The placebo effect — the phenomenon in which patients experience real improvements after receiving inactive treatments — has long been considered a nuisance in clinical research, something to be controlled for rather than studied in its own right. Recently, however, neuroscientists have begun to investigate the placebo effect as a legitimate biological phenomenon. Brain imaging studies have shown that placebos can trigger the release of endorphins and dopamine, producing measurable changes in neural activity. Some researchers now argue that harnessing the placebo effect could complement conventional treatments, potentially reducing the dosages of medications needed and their associated side effects. Critics counter that deliberately administering placebos raises serious ethical concerns about informed consent and medical deception.",questions:[
    {question:"According to the passage, the placebo effect was traditionally viewed by researchers as",choices:["a powerful therapeutic tool","a methodological obstacle to overcome","evidence against drug effectiveness","a purely psychological phenomenon with no physical basis","an ethical violation in medical practice"],correct:1,explanation:"The passage states the placebo effect was 'considered a nuisance in clinical research, something to be controlled for rather than studied.' This frames it as a methodological problem — an obstacle that complicated drug trials."},
    {question:"The mention of brain imaging studies serves to",choices:["prove that all medications are merely placebos","establish that the placebo effect has a physical basis","argue against the use of placebos in research","demonstrate that neuroscience is superior to other fields","criticize traditional medical practices"],correct:1,explanation:"Brain imaging showing 'release of endorphins and dopamine' and 'measurable changes in neural activity' provides physical evidence that the placebo effect is a real biological phenomenon, not just a psychological trick."},
    {question:"The passage suggests that incorporating placebos into medical treatment would be",choices:["universally beneficial with no drawbacks","potentially useful but ethically complicated","impossible given current technology","supported by all medical professionals","harmful to patient outcomes"],correct:1,explanation:"The passage presents both potential benefits ('reducing dosages,' 'complementing conventional treatments') and ethical concerns ('informed consent,' 'medical deception'). This balanced view matches option B: potentially useful but ethically complicated."}
  ],difficulty:2,tags:["science","medicine"]},

  {id:"rc7",passage:"Language extinction is occurring at an alarming rate, with linguists estimating that roughly half of the world's approximately 7,000 languages will disappear by the end of this century. Each language that vanishes takes with it a unique way of categorizing and understanding the world. The Hopi language, for example, conceptualizes time differently from European languages, lacking the past-present-future tense system that speakers of English take for granted. When a language dies, the particular knowledge encoded in its vocabulary — specialized terms for local plants, animals, and ecological relationships that have no equivalents in dominant languages — is lost as well. Critics of language preservation efforts argue that linguistic consolidation is a natural and even beneficial process, facilitating global communication and economic participation. Preservationists counter that the analogy to biological extinction is apt: just as biodiversity strengthens ecosystems, linguistic diversity enriches human culture and cognitive capacity.",questions:[
    {question:"The primary purpose of the Hopi language example is to",choices:["argue that Hopi is superior to English","demonstrate that different languages embody different worldviews","criticize European languages for their limitations","propose that all languages adopt the Hopi time system","illustrate that some languages are more complex than others"],correct:1,explanation:"The Hopi example illustrates the passage's claim that each language carries 'a unique way of categorizing and understanding the world.' Hopi conceptualizes time differently — showing that language shapes worldview."},
    {question:"Preservationists would most likely respond to critics by arguing that",choices:["global communication is undesirable","economic participation is overrated","linguistic diversity serves important functions analogous to biodiversity","all languages will eventually converge into one","language preservation is too expensive to pursue"],correct:2,explanation:"The passage directly states that preservationists compare linguistic diversity to biodiversity, arguing both 'strengthen' their respective domains. They counter that diversity has functional value, not just cultural significance."}
  ],difficulty:2,tags:["linguistics","culture"]},

  {id:"rc8",passage:"The concept of meritocracy — the idea that advancement should be based on individual ability and effort rather than birth or privilege — is nearly universally endorsed in modern democracies. Yet sociologists have increasingly questioned whether true meritocracy exists in practice. Research consistently shows that socioeconomic background remains the strongest predictor of educational and professional success, even after controlling for measured ability. Children born into wealthy families have access to better nutrition, healthcare, schools, and social networks — advantages that compound over time and translate into opportunities that appear to be earned through merit alone. The meritocratic ideal, these scholars suggest, may actually serve to legitimize inequality by implying that those at the bottom of the social hierarchy deserve their position.",questions:[
    {question:"The passage suggests that the concept of meritocracy may be problematic because it",choices:["encourages people to work harder than necessary","fails to account for systemic advantages that influence outcomes","was invented by wealthy elites to maintain power","has been proven to be entirely false by sociological research","discourages charitable giving to those in need"],correct:1,explanation:"The passage argues that meritocracy overlooks how 'socioeconomic background remains the strongest predictor of success' and that advantages 'compound over time.' Meritocracy is problematic because it ignores these systemic, compounding advantages."},
    {question:"The phrase 'advantages that compound over time' most likely means that",choices:["wealthy children become increasingly resentful of others","initial advantages grow and produce additional advantages","all advantages eventually disappear with age","compounding only applies to financial investments","wealthy and poor children converge in ability over time"],correct:1,explanation:"'Compound' in this context works like compound interest — early advantages (nutrition, schools, networks) lead to further advantages, which lead to more advantages. The gap widens rather than narrows over time."},
    {question:"The author would most likely agree that",choices:["meritocracy should be abolished entirely","individual effort plays no role in success","the ideal of meritocracy and its reality often diverge","wealthy people never deserve their success","education has no effect on social mobility"],correct:2,explanation:"The passage contrasts the meritocratic 'ideal' (universally endorsed) with the sociological 'reality' (background predicts success more than ability). The author's position is that the ideal and reality don't match — they diverge."}
  ],difficulty:2,tags:["sociology","inequality"]},

  {id:"rc9",passage:"Artificial intelligence systems trained on large datasets inevitably absorb and reproduce the biases present in their training data. When a facial recognition system is trained primarily on images of light-skinned faces, it performs poorly on darker-skinned individuals — not because of any explicit programming but because the training data underrepresented certain populations. This has led to documented cases of wrongful identification by law enforcement systems. The challenge is compounded by the opacity of many AI systems: complex neural networks operate as 'black boxes' whose decision-making processes are difficult even for their creators to fully explain. Some researchers advocate for mandatory algorithmic auditing, while others argue that the focus should be on diversifying training data and development teams rather than regulating outputs.",questions:[
    {question:"According to the passage, AI bias primarily results from",choices:["intentional programming by prejudiced developers","the mathematical limitations of neural networks","unrepresentative training data","government interference in technology development","the inherent inferiority of AI compared to humans"],correct:2,explanation:"The passage explicitly states that bias comes 'not because of any explicit programming but because the training data underrepresented certain populations.' The cause is the data, not the intent."},
    {question:"The term 'black boxes' is used to describe AI systems that",choices:["are physically housed in dark containers","operate through processes that are not easily understood","are designed to be deliberately secretive","only work in controlled laboratory settings","have been banned by regulators"],correct:1,explanation:"The passage defines 'black boxes' as systems 'whose decision-making processes are difficult even for their creators to fully explain.' The metaphor refers to opacity/lack of transparency in how decisions are made."}
  ],difficulty:1,tags:["technology","ethics"]},

  {id:"rc10",passage:"The debate over whether great leaders are born or made has persisted for centuries, but contemporary leadership research suggests the question itself may be poorly framed. While certain personality traits — such as extraversion, conscientiousness, and emotional stability — are correlated with leadership effectiveness, these traits account for only a modest portion of the variance in leadership outcomes. Situational factors, including organizational culture, team composition, and the specific challenges facing an institution, often matter more than individual characteristics. Furthermore, research on leadership development programs indicates that many leadership skills can be taught and improved through deliberate practice, though the degree of improvement varies considerably among individuals. The most accurate characterization may be that effective leadership emerges from the interaction between innate tendencies, learned skills, and environmental demands.",questions:[
    {question:"The author suggests that the 'born or made' question about leadership is",choices:["definitively answered by current research","a false dichotomy that oversimplifies a complex phenomenon","more relevant today than in previous centuries","easily resolved by studying personality traits","unimportant and not worth investigating"],correct:1,explanation:"The author states the question 'may be poorly framed' and concludes that leadership 'emerges from the interaction between innate tendencies, learned skills, and environmental demands.' This means it's neither purely born nor made — the either/or framing is a false dichotomy."},
    {question:"According to the passage, personality traits such as extraversion",choices:["are the primary determinant of leadership success","have no relationship to leadership effectiveness","are somewhat predictive but far from the whole picture","can be easily changed through training programs","are less important than physical appearance"],correct:2,explanation:"The passage says traits are 'correlated with leadership effectiveness' (they matter) but 'account for only a modest portion of the variance' (they're not the whole story). This matches option C: somewhat predictive but not determinative."},
    {question:"The passage's conclusion about leadership can best be described as",choices:["a strong endorsement of the 'born' position","a definitive argument for the 'made' position","an integrative view that combines multiple factors","a rejection of all previous leadership research","an argument that leadership cannot be studied scientifically"],correct:2,explanation:"The final sentence explicitly offers an integrative conclusion: leadership comes from 'the interaction between innate tendencies, learned skills, and environmental demands' — combining nature, nurture, and context."}
  ],difficulty:2,tags:["psychology","leadership"]}
];
