// Reading Comprehension Questions — Batch 2 (ETS/Magoosh/Barron's style)
const RC_DATA_2 = [
  {id:"rc11",passage:"The prevailing view among economists has long been that free trade benefits all participating nations through comparative advantage — each country specializes in producing goods for which it has the lowest opportunity cost. However, this theoretical framework assumes conditions that rarely hold in practice: perfectly mobile labor, zero transition costs, and rational actors with complete information. When a manufacturing plant closes in a small town because production has moved overseas, the displaced workers cannot simply retrain as software engineers overnight. The communities built around these industries face devastating economic and social consequences that aggregate statistics about GDP growth conveniently obscure. Critics argue that trade policy must account for these distributional effects rather than simply pointing to net gains that may be concentrated among the already wealthy.",questions:[
    {question:"The author's primary purpose is to",choices:["argue that free trade should be abolished entirely","highlight limitations of the standard economic argument for free trade","prove that trade deficits cause unemployment","compare the economies of developed and developing nations","propose specific reforms to existing trade agreements"],correct:1,explanation:"The passage presents the 'prevailing view' of free trade, then systematically identifies its unrealistic assumptions and overlooked consequences. The purpose is to expose limitations, not to reject trade entirely (A) or propose solutions (E)."},
    {question:"The author mentions 'perfectly mobile labor' primarily to",choices:["describe the current state of the job market","illustrate one of the unrealistic assumptions underlying free trade theory","advocate for government retraining programs","explain why some workers earn more than others","praise the flexibility of the modern workforce"],correct:1,explanation:"'Perfectly mobile labor' is listed among 'conditions that rarely hold in practice' — it's presented as an unrealistic assumption of the theory, showing the gap between the model and reality."},
    {question:"The phrase 'conveniently obscure' (line 7) suggests that aggregate GDP statistics",choices:["are intentionally fabricated to deceive the public","hide the unequal distribution of trade's benefits and costs","are too complex for ordinary citizens to understand","accurately represent the economic situation of all citizens","should be replaced with different measurements"],correct:1,explanation:"'Conveniently obscure' implies that GDP statistics, while technically accurate, mask the reality that gains go to some while losses fall on others. The word 'conveniently' suggests this obscuring serves certain interests."}
  ],difficulty:2,tags:["economics","argument"]},

  {id:"rc12",passage:"The question of whether animals possess consciousness — subjective inner experience — remains one of the most contentious issues in philosophy of mind. Behaviorists long maintained that attributing mental states to animals was unscientific anthropomorphism, since we can only observe behavior, not internal experience. Yet recent neuroscience has complicated this position considerably. Brain imaging studies reveal that mammals, birds, and even some invertebrates possess neural structures associated with conscious experience in humans. The Cambridge Declaration on Consciousness, signed by a group of prominent neuroscientists in 2012, formally acknowledged that many non-human animals possess the neurological substrates that generate consciousness. Nevertheless, the so-called 'hard problem' of consciousness — explaining why and how physical processes give rise to subjective experience — applies equally to human and animal minds, making definitive claims about animal consciousness inherently speculative.",questions:[
    {question:"The passage suggests that the Cambridge Declaration was significant because it",choices:["solved the hard problem of consciousness","proved definitively that animals are conscious","represented scientific acknowledgment that animals likely have conscious experience","rejected all previous behaviorist research","established legal rights for animals"],correct:2,explanation:"The Declaration 'formally acknowledged' that animals possess neural structures associated with consciousness. This is significant as a formal scientific recognition, but the passage notes that definitive claims remain 'speculative' — so it's acknowledgment, not proof (B)."},
    {question:"The author would most likely agree that",choices:["only humans possess consciousness","behaviorists were entirely correct in their approach","the question of animal consciousness cannot currently be definitively resolved","neuroscience has conclusively proven animal consciousness","consciousness is unrelated to neural structures"],correct:2,explanation:"The passage ends by noting that the 'hard problem' makes 'definitive claims inherently speculative' — we have strong suggestive evidence but cannot conclusively resolve the question. This balanced view acknowledges both evidence and uncertainty."}
  ],difficulty:2,tags:["philosophy","science"]},

  {id:"rc13",passage:"Urban planners have increasingly embraced the concept of the '15-minute city' — a model in which all essential services, from groceries to healthcare to parks, are accessible within a 15-minute walk or bike ride from any residence. Proponents argue that such cities reduce car dependence, lower carbon emissions, promote physical health, and strengthen community bonds by encouraging local interaction. However, implementing this vision faces substantial obstacles. Existing zoning laws in many cities strictly separate residential, commercial, and industrial areas — a legacy of early 20th-century planning that was itself a reaction to the genuine health hazards of living adjacent to heavy industry. Converting car-centric suburban sprawl into walkable neighborhoods requires not just rezoning but massive infrastructure investment in sidewalks, bike lanes, and public transit. Critics also note that the 15-minute city concept may inadvertently reinforce socioeconomic segregation, as wealthier neighborhoods are more likely to attract the amenities that make the model viable.",questions:[
    {question:"According to the passage, strict zoning separation originated as a response to",choices:["suburban sprawl","climate change concerns","health dangers of proximity to industrial areas","the automobile industry's lobbying","economic inequality between neighborhoods"],correct:2,explanation:"The passage explicitly states that separating residential from industrial areas was 'a reaction to the genuine health hazards of living adjacent to heavy industry.' Early zoning addressed real public health problems."},
    {question:"The passage implies that the 15-minute city model could worsen inequality because",choices:["it would raise property taxes uniformly","wealthy areas are better positioned to attract necessary services","public transit primarily benefits wealthy commuters","zoning changes are always regressive","only wealthy people can walk or ride bikes"],correct:1,explanation:"The passage states that 'wealthier neighborhoods are more likely to attract the amenities' needed for the model, suggesting affluent areas would achieve the 15-minute ideal while poorer areas would not."},
    {question:"The author's attitude toward the 15-minute city concept is best described as",choices:["wholly enthusiastic","cautiously supportive but aware of complications","dismissive and skeptical","neutral and disinterested","hostile and opposed"],correct:1,explanation:"The author presents the concept's benefits ('reduce car dependence, lower emissions, promote health') but then thoroughly discusses obstacles and risks. This balanced treatment = cautious support with honest assessment of challenges."}
  ],difficulty:2,tags:["urban planning","policy"]},

  {id:"rc14",passage:"The replication crisis in social psychology — the discovery that many celebrated findings fail to hold up when other laboratories attempt to reproduce them — has forced a fundamental reckoning within the discipline. Studies that once formed the bedrock of introductory textbooks, from priming effects on behavior to ego depletion theory, have either failed to replicate or shown dramatically smaller effect sizes than originally reported. The causes are multifaceted: publication bias favoring positive results, small sample sizes that inflate effect estimates, researcher degrees of freedom that allow unconscious manipulation of analyses, and institutional incentives that reward novelty over rigor. Rather than viewing the replication crisis as a catastrophe, however, many psychologists see it as a healthy corrective. New practices — pre-registration of hypotheses, larger sample sizes, open data sharing, and registered reports — are producing more reliable findings, even if they are less dramatic than those of the previous era.",questions:[
    {question:"The passage suggests that publication bias contributes to the replication crisis because",choices:["publishers deliberately falsify results","journals prefer to publish studies with positive findings, creating a distorted literature","only large universities can afford to publish research","replication studies are too expensive to conduct","negative results are inherently less valid than positive ones"],correct:1,explanation:"'Publication bias favoring positive results' means journals preferentially publish studies that find something, creating a literature where failures to find effects are systematically hidden. This creates a false impression of the evidence."},
    {question:"The phrase 'researcher degrees of freedom' most likely refers to",choices:["academic tenure protections","the flexibility researchers have in analyzing data, which can lead to biased results","the number of publications a researcher needs for promotion","geographic mobility of academics","the right to choose one's own research topics"],correct:1,explanation:"In context, 'researcher degrees of freedom that allow unconscious manipulation of analyses' = the many choices researchers make in analyzing data (which variables to include, which to exclude, when to stop collecting data) that can, even unconsciously, steer results."},
    {question:"The author characterizes the replication crisis primarily as",choices:["an existential threat to psychology as a discipline","a painful but ultimately beneficial process of self-correction","evidence that social psychology produces no valid findings","a problem limited to a few dishonest researchers","an issue that has already been fully resolved"],correct:1,explanation:"The passage calls it a 'healthy corrective' and describes new practices 'producing more reliable findings.' The crisis is framed as painful ('forced a fundamental reckoning') but positive in its long-term effects on scientific quality."}
  ],difficulty:2,tags:["science","methodology"]},

  {id:"rc15",passage:"The debate over reparations for slavery in the United States is not merely a question of historical justice but also a practical challenge of staggering complexity. Proponents argue that the economic consequences of slavery — compounded by subsequent decades of discriminatory policies including Jim Crow laws, redlining, and unequal access to the GI Bill — have created a racial wealth gap that persists to this day. Studies consistently show that the median white household holds approximately ten times the wealth of the median Black household, a disparity that cannot be explained by differences in education or income alone. Opponents raise numerous objections: the difficulty of identifying specific beneficiaries, the question of whether individuals who never owned slaves bear responsibility, and concerns that cash payments could be politically divisive without addressing structural inequalities. Some scholars have proposed alternatives to direct payments, including targeted investments in education, housing, and healthcare in historically disadvantaged communities — an approach they argue would address root causes more effectively while building broader political support.",questions:[
    {question:"The passage mentions the GI Bill primarily to",choices:["praise its positive effects on American society","illustrate how discriminatory policies compounded the legacy of slavery","argue that military service should be rewarded","compare educational opportunities across racial groups","suggest that new legislation should model the GI Bill"],correct:1,explanation:"The GI Bill is listed alongside Jim Crow and redlining as a 'discriminatory policy' that compounded slavery's economic effects. The point is that discrimination didn't end with abolition — it continued through policies that appeared race-neutral but weren't."},
    {question:"Which of the following would the 'scholars' mentioned in the final sentence most likely support?",choices:["Direct cash payments to descendants of enslaved people","Doing nothing, as slavery ended over 150 years ago","Government investment in schools and hospitals in historically Black neighborhoods","Reparations funded entirely by descendants of slave owners","A national apology without any financial component"],correct:2,explanation:"These scholars propose 'targeted investments in education, housing, and healthcare in historically disadvantaged communities' — option C matches this directly. They favor structural investment over direct payments."}
  ],difficulty:2,tags:["social policy","history"]},

  {id:"rc16",passage:"Contrary to popular belief, the scientific method is not a single, fixed procedure but rather a family of approaches united by a commitment to empirical evidence and logical reasoning. The controlled laboratory experiment — manipulating one variable while holding others constant — is only one tool in the scientist's repertoire. Astronomers cannot manipulate galaxies; they must rely on observation and mathematical modeling. Evolutionary biologists cannot rerun millions of years of natural selection; they draw inferences from fossil records, genetic data, and comparative anatomy. Even within experimental sciences, the process is far messier than textbook descriptions suggest: hypotheses often emerge from unexpected observations rather than pure deduction, experiments frequently produce ambiguous results requiring judgment calls about interpretation, and scientific consensus develops through a social process of peer review, debate, and gradual persuasion rather than through single decisive experiments.",questions:[
    {question:"The author's primary argument is that",choices:["the scientific method is fundamentally flawed","astronomy is more scientific than biology","science is a more varied and complex process than commonly portrayed","controlled experiments are the only valid form of scientific inquiry","scientific consensus is unreliable because it is a social process"],correct:2,explanation:"The passage's thesis is that science is not 'a single, fixed procedure' but 'a family of approaches' — and the practice is 'far messier than textbook descriptions suggest.' The author is correcting an oversimplified popular understanding."},
    {question:"The examples of astronomy and evolutionary biology serve to illustrate that",choices:["these fields are less rigorous than physics or chemistry","some scientific disciplines cannot use controlled experiments but are nonetheless valid","scientists in these fields should switch to experimental methods","observational evidence is always superior to experimental evidence","the scientific method is not applicable to studying the past"],correct:1,explanation:"Astronomers 'cannot manipulate galaxies' and biologists 'cannot rerun natural selection' — yet both are genuine sciences. The examples show that legitimate science exists beyond the controlled experiment."}
  ],difficulty:1,tags:["science","methodology"]},

  {id:"rc17",passage:"The concept of emotional intelligence — the ability to recognize, understand, and manage one's own emotions and those of others — has gained enormous popularity since Daniel Goleman's 1995 bestseller brought it to public attention. Corporate training programs now routinely promise to boost employees' emotional intelligence, and some researchers have claimed that emotional intelligence predicts professional success more reliably than IQ. However, the scientific evidence for these sweeping claims remains surprisingly thin. Meta-analyses have found that emotional intelligence measures overlap substantially with existing personality traits, particularly agreeableness and emotional stability from the Big Five model, raising the question of whether emotional intelligence represents a genuinely distinct construct or merely repackages familiar concepts under a marketable label. Furthermore, the relationship between emotional intelligence and job performance, while statistically significant, is modest and varies considerably across different occupations and contexts.",questions:[
    {question:"The passage suggests that the popularity of emotional intelligence may exceed",choices:["its practical usefulness","its scientific support","its historical importance","public interest in the concept","corporate willingness to invest in training"],correct:1,explanation:"The passage contrasts 'enormous popularity' with 'surprisingly thin' scientific evidence. The gap between popularity and evidence is the central tension of the passage."},
    {question:"The author raises the overlap with Big Five personality traits to suggest that emotional intelligence might",choices:["be more important than previously thought","represent a truly revolutionary concept","simply rebrand existing psychological constructs rather than identifying something new","be impossible to measure accurately","have no relationship to personality at all"],correct:2,explanation:"If emotional intelligence 'overlaps substantially' with existing traits, it may merely 'repackage familiar concepts under a marketable label' rather than identifying something genuinely new. Same wine, new bottle."},
    {question:"The author's tone throughout the passage is best described as",choices:["dismissive and hostile toward emotional intelligence","enthusiastically supportive of Goleman's work","analytically skeptical while acknowledging the concept's appeal","indifferent to the entire debate","passionately advocating for traditional IQ measures"],correct:2,explanation:"The author acknowledges emotional intelligence's 'enormous popularity' and notes the relationship to performance is 'statistically significant' — but raises important doubts about the evidence. This is measured skepticism, not outright rejection."}
  ],difficulty:2,tags:["psychology","critique"]},

  {id:"rc18",passage:"The decline of local journalism in the United States represents not merely an economic disruption but a democratic crisis. Between 2005 and 2020, approximately 2,100 newspapers closed, creating vast 'news deserts' — communities with no dedicated local news coverage. Research has documented the consequences: in areas that lose local newspapers, voter turnout decreases, municipal borrowing costs rise (as reduced media scrutiny allows less efficient governance), and corruption tends to increase. The digital revolution that destroyed the advertising revenue model sustaining local papers has not produced adequate replacements. While national outlets and social media platforms provide abundant commentary on federal politics, they largely ignore the school board meetings, city council votes, and local court proceedings that most directly affect citizens' daily lives. Various proposed solutions — nonprofit newsrooms, philanthropic funding, government subsidies — each face significant challenges, from sustainability concerns to fears about editorial independence.",questions:[
    {question:"The passage primarily argues that the decline of local journalism",choices:["is a natural and inevitable consequence of technological progress","poses a threat to democratic governance at the community level","has been offset by the rise of social media","affects only rural communities","is primarily an economic problem with no political implications"],correct:1,explanation:"The passage frames the decline as 'a democratic crisis,' citing decreased voter turnout, increased corruption, and reduced government accountability. The argument is fundamentally about democracy, not just economics."},
    {question:"The author mentions municipal borrowing costs to illustrate that",choices:["local governments are spending too much money","newspapers helped keep local government accountable and efficient","investors should avoid municipal bonds","local journalism was focused on financial reporting","government subsidies could replace newspaper revenue"],correct:1,explanation:"Rising borrowing costs after newspapers close shows that media scrutiny kept government efficient. Without watchdog journalism, governance becomes 'less efficient' — and that inefficiency has measurable financial consequences."},
    {question:"Based on the passage, social media fails as a replacement for local newspapers because it",choices:["is controlled by a few large corporations","does not cover the local governance issues that most affect communities","is too expensive for most people to access","only provides entertainment, not news","has been banned in many communities"],correct:1,explanation:"The passage states that social media platforms 'largely ignore the school board meetings, city council votes, and local court proceedings' — the hyper-local coverage that matters most for democratic accountability."}
  ],difficulty:1,tags:["media","democracy"]},

  {id:"rc19",passage:"The notion that taste in food is purely subjective — that there is no accounting for taste, as the old saying goes — is surprisingly difficult to defend once examined closely. While individual preferences certainly vary, research in food science reveals that our perception of flavor is shaped by measurable chemical compounds interacting with specific receptors, that certain combinations of flavors produce objectively more complex taste experiences than others, and that trained palates can reliably distinguish quality differences that untrained tasters cannot. The parallel with visual art is instructive: while everyone is entitled to their aesthetic preferences, we recognize that a trained art critic possesses knowledge and perceptual skills that enable more informed judgments than those of a casual museum visitor. The subjectivist position mistakes the undeniable diversity of preferences for the absence of any standards whatsoever — conflating the fact that people disagree with the claim that no one can be more right than anyone else.",questions:[
    {question:"The author's main argument is that",choices:["food preferences are entirely determined by biology","taste in food involves objective elements that can be evaluated, not just personal preference","trained food critics are always correct","all people should eat the same foods","subjective preferences in food do not exist"],correct:1,explanation:"The passage argues against pure subjectivism — taste is not ONLY personal preference. There are 'measurable chemical compounds,' 'objectively more complex taste experiences,' and trained palates that can distinguish quality. But the author doesn't deny that preferences vary (A, E)."},
    {question:"The comparison to visual art criticism serves to",choices:["argue that food criticism is more important than art criticism","suggest that ordinary people's opinions about food are worthless","illustrate that expertise can lead to more informed judgments in matters of taste","prove that all aesthetic judgments are purely objective","establish that art and food are identical experiences"],correct:2,explanation:"The art parallel makes the point that while preferences vary, expertise enables 'more informed judgments' — just as in food. It's about the value of training and knowledge, not the worthlessness of lay opinions (B)."}
  ],difficulty:2,tags:["philosophy","argument"]},

  {id:"rc20",passage:"The Green Revolution of the 1960s and 1970s — which introduced high-yield crop varieties, synthetic fertilizers, and modern irrigation to developing countries — is credited with averting widespread famine and saving an estimated one billion lives. Yet its legacy is deeply ambivalent. While crop yields increased dramatically, the new agricultural methods required expensive inputs that favored larger, wealthier farmers, accelerating rural inequality and displacing smallholders who could not compete. The heavy reliance on chemical fertilizers and pesticides degraded soil quality, contaminated water supplies, and reduced biodiversity. Monoculture farming — the practice of growing a single crop variety over vast areas — made food systems vulnerable to disease outbreaks and climate variations. Contemporary agricultural researchers now advocate for approaches that integrate the productivity gains of the Green Revolution with more sustainable practices: crop diversification, reduced chemical inputs, and farming methods adapted to local ecological conditions.",questions:[
    {question:"The passage characterizes the Green Revolution's legacy as 'deeply ambivalent' because",choices:["it failed completely to increase food production","its benefits were accompanied by significant negative consequences","no one can agree on whether it actually happened","its technology was too primitive to be useful","it only benefited wealthy Western nations"],correct:1,explanation:"'Ambivalent' = mixed feelings. The Revolution saved a billion lives (positive) BUT increased inequality, degraded soil, contaminated water, and reduced biodiversity (negative). Both truths exist simultaneously."},
    {question:"Contemporary agricultural researchers would most likely advocate for",choices:["returning entirely to pre-Green Revolution farming methods","continuing to increase chemical fertilizer use","growing a single high-yield crop variety in every region","combining high-yield techniques with environmentally sustainable practices","abandoning agriculture in favor of synthetic food production"],correct:3,explanation:"The passage says researchers advocate 'integrating productivity gains with sustainable practices' — combining the best of modern agriculture with environmental responsibility. This matches option D."},
    {question:"The passage implies that monoculture farming is problematic primarily because it",choices:["reduces crop yields compared to diversified farming","creates excessive food variety in markets","makes agricultural systems fragile and susceptible to catastrophic failure","requires too much labor to maintain","is only possible in tropical climates"],correct:2,explanation:"Monoculture 'made food systems vulnerable to disease outbreaks and climate variations' — one disease could wipe out an entire harvest if everything is the same crop. Diversity = resilience; uniformity = fragility."}
  ],difficulty:2,tags:["agriculture","environment"]},

  {id:"rc21",passage:"The phenomenon of 'moral licensing' — in which performing a virtuous act in one domain provides psychological permission to behave less virtuously in another — poses a significant challenge to conventional approaches to promoting ethical behavior. Studies have shown that people who purchase environmentally friendly products subsequently feel licensed to act less environmentally conscious in other areas, that expressing egalitarian attitudes can paradoxically free individuals to make biased decisions later, and that donating to charity can reduce support for systemic reforms that would address the same issues more effectively. The mechanism appears to involve a kind of moral bookkeeping: good deeds create a psychological credit balance that can be 'spent' on self-interested behavior without triggering guilt. This suggests that moral progress may not be achievable through isolated good acts but may require more fundamental changes in how people understand their ethical obligations.",questions:[
    {question:"According to the passage, moral licensing is problematic because it",choices:["prevents people from ever doing good deeds","causes people to use good behavior as justification for subsequent bad behavior","makes charitable donations ineffective","only affects wealthy individuals","is a theory with no empirical support"],correct:1,explanation:"The core problem is that 'performing a virtuous act provides psychological permission to behave less virtuously' — good behavior becomes a license for bad behavior, undermining the net moral effect."},
    {question:"The 'moral bookkeeping' metaphor suggests that people",choices:["carefully track all their financial transactions","treat moral behavior like a bank account where deposits of virtue allow withdrawals of self-interest","never feel guilt about their actions","are incapable of genuine moral behavior","only behave ethically when financially incentivized"],correct:1,explanation:"'Good deeds create a psychological credit balance that can be spent on self-interested behavior' — exactly like a bank account. Deposit virtue, withdraw selfishness, balance maintained."}
  ],difficulty:2,tags:["psychology","ethics"]},

  {id:"rc22",passage:"The rise of algorithmic content curation — in which platforms use machine learning to determine what information users see — has fundamentally altered the public sphere. Unlike traditional media gatekeepers such as newspaper editors, who operate according to professional norms of journalistic integrity, algorithms optimize for a single metric: user engagement. Content that provokes strong emotional reactions, regardless of its accuracy or social value, is systematically promoted because it generates more clicks, shares, and time on platform. The result is what scholars call an 'attention economy' in which the most extreme, inflammatory, and outrage-inducing content has a structural advantage over measured, nuanced, and factually complex reporting. This is not a conspiracy but an emergent property of systems designed to maximize engagement: no programmer explicitly decided to promote misinformation, but the incentive structure reliably produces that outcome.",questions:[
    {question:"The passage suggests that algorithmic curation differs from traditional editorial gatekeeping primarily in",choices:["the technology used to distribute information","the criteria used to determine what content is promoted","the number of people who see the content","the cost of producing content","the speed at which information travels"],correct:1,explanation:"The key difference is criteria: editors use 'professional norms of journalistic integrity' while algorithms optimize for 'user engagement.' Same function (deciding what people see), fundamentally different values driving the decisions."},
    {question:"The author characterizes the promotion of misinformation by algorithms as",choices:["a deliberate conspiracy by tech companies","an unintended but predictable consequence of engagement-driven design","a problem that has been exaggerated by critics","easily solved through better programming","unique to social media platforms"],correct:1,explanation:"'No programmer explicitly decided to promote misinformation, but the incentive structure reliably produces that outcome' — it's unintended (not a conspiracy) but predictable (a structural/systemic outcome of the design)."},
    {question:"Based on the passage, 'measured, nuanced, and factually complex reporting' is disadvantaged in the attention economy because it",choices:["is more expensive to produce","generates less emotional engagement than extreme content","is written at too high a reading level","is only available behind paywalls","is produced less frequently than sensational content"],correct:1,explanation:"The passage states that content provoking 'strong emotional reactions' is promoted while nuanced reporting has a 'structural disadvantage.' The issue is engagement: calm, complex analysis doesn't trigger the clicks that extreme content does."}
  ],difficulty:2,tags:["technology","media"]},

  {id:"rc23",passage:"Bilingual individuals do not simply possess two separate language systems operating in isolation; rather, both languages are simultaneously active in the brain, even when only one is being used. This constant co-activation requires the brain to continuously manage competition between languages — selecting the appropriate language while suppressing the other. Researchers hypothesize that this ongoing executive control exercise strengthens general cognitive abilities, particularly in tasks requiring attention, inhibition, and mental flexibility. Studies have found that bilingual children outperform monolingual peers on tasks requiring them to ignore irrelevant information or switch between competing rules, and that bilingual adults show delayed onset of dementia symptoms by an average of four to five years. However, recent large-scale studies have challenged the magnitude of these advantages, suggesting that the 'bilingual advantage' in executive function may be smaller than initially reported and more dependent on specific circumstances than previously believed.",questions:[
    {question:"The passage suggests that the cognitive benefits of bilingualism arise from",choices:["having a larger vocabulary in total","the mental exercise of constantly managing two competing language systems","speaking languages with different grammatical structures","learning languages at an early age","reading literature in multiple languages"],correct:1,explanation:"The passage directly states that 'constant co-activation requires the brain to continuously manage competition' and this 'ongoing executive control exercise strengthens general cognitive abilities.' The benefit comes from the mental workout of managing two systems."},
    {question:"The author mentions the delayed onset of dementia to",choices:["argue that everyone should learn a second language immediately","provide evidence for the cognitive benefits of bilingualism","suggest that bilingualism is a cure for dementia","compare bilingual and monolingual brain structures","criticize monolingual education policies"],correct:1,explanation:"The dementia finding is presented as supporting evidence for cognitive benefits — one of several studies showing bilingual advantages. It's evidence, not a cure (C) or policy argument (E)."},
    {question:"The final sentence of the passage serves to",choices:["completely refute the bilingual advantage hypothesis","qualify earlier claims by noting that the advantage may be less dramatic than thought","introduce an entirely new topic","argue that monolingualism is superior to bilingualism","dismiss all previous research on bilingualism"],correct:1,explanation:"'Recent studies have challenged the magnitude' and suggest the advantage 'may be smaller than initially reported' — this qualifies (adds nuance to) the earlier claims without rejecting them entirely."}
  ],difficulty:2,tags:["linguistics","neuroscience"]},

  {id:"rc24",passage:"The tension between economic development and environmental preservation is often framed as an inevitable trade-off: societies must choose between growth and a healthy planet. This framing, however, obscures a more complex reality. Environmental degradation itself imposes enormous economic costs — from healthcare expenses associated with pollution to agricultural losses from soil degradation to the staggering price of climate-related disasters. A World Bank study estimated that air pollution alone costs the global economy over $5 trillion annually in welfare losses. Moreover, the clean energy transition is increasingly driven not by altruism but by economics: in most markets, solar and wind power are now cheaper than new fossil fuel plants. The companies and nations that develop green technologies will capture the industries of the future, while those clinging to fossil fuels risk being left with stranded assets and obsolete infrastructure. The real trade-off may not be between economy and environment but between short-term convenience and long-term prosperity.",questions:[
    {question:"The author's central argument is that",choices:["environmental protection always costs more than it saves","economic growth and environmental protection are fundamentally incompatible","the apparent trade-off between economy and environment is misleading because environmental damage has huge economic costs","developing nations should prioritize growth over environmental concerns","the clean energy transition will increase energy costs"],correct:2,explanation:"The passage directly challenges the 'inevitable trade-off' framing, arguing that environmental damage IS an economic cost, and clean energy IS economically competitive. The apparent conflict dissolves under closer examination."},
    {question:"The World Bank air pollution statistic serves primarily to",choices:["criticize the World Bank's methodology","quantify the economic cost of environmental degradation","argue that air quality regulations are too strict","compare pollution levels across different countries","demonstrate that economic research is unreliable"],correct:1,explanation:"The $5 trillion figure is presented to make the abstract argument concrete: environmental damage has a specific, enormous price tag. It supports the argument that environment vs. economy is a false choice."}
  ],difficulty:1,tags:["economics","environment"]},

  {id:"rc25",passage:"The concept of 'impostor syndrome' — the persistent feeling of being a fraud despite evidence of competence — was first described by psychologists Pauline Clance and Suzanne Imes in 1978 among high-achieving women. Subsequent research has shown that the phenomenon is far more widespread, affecting people across genders, professions, and achievement levels. Paradoxically, impostor syndrome tends to be most acute among the most accomplished individuals; those with genuine expertise are more aware of the vast landscape of what they do not know, while the less knowledgeable often lack the awareness to recognize their own limitations — a related phenomenon known as the Dunning-Kruger effect. Some scholars have questioned whether impostor syndrome should be considered a clinical condition at all, arguing that it is better understood as a natural response to environments that historically excluded certain groups and continue to signal that they do not belong.",questions:[
    {question:"The passage mentions the Dunning-Kruger effect to",choices:["contradict the existence of impostor syndrome","explain why less competent people are often more confident than experts","argue that all psychological research is flawed","suggest that impostor syndrome only affects women","demonstrate that expertise leads to overconfidence"],correct:1,explanation:"Dunning-Kruger is introduced as a 'related phenomenon' that completes the paradox: experts doubt themselves (impostor syndrome) because they see how much they don't know, while the less knowledgeable 'lack the awareness to recognize their own limitations' — ignorance breeds confidence."},
    {question:"The scholars mentioned in the final sentence would most likely argue that",choices:["impostor syndrome is entirely imaginary","feeling like an impostor is always irrational","some feelings of not belonging reflect real systemic biases rather than individual pathology","impostor syndrome should be treated exclusively with medication","only members of historically excluded groups experience impostor syndrome"],correct:2,explanation:"These scholars argue impostor syndrome is 'a natural response to environments that historically excluded certain groups' — meaning it reflects real social conditions (systematic exclusion signals), not just individual psychology. The feeling maps onto reality."}
  ],difficulty:2,tags:["psychology","identity"]}
];
