// Sentence Equivalence Questions — GRE-style
// Format: sentence with 1 blank, 6 choices, pick exactly 2 that give same meaning
const SE_DATA = [
  {id:"se1",sentence:"The professor's explanation was so _____ that even students with no background in physics could follow the argument easily.",choices:["abstruse","lucid","convoluted","pellucid","esoteric","recondite"],correct:[1,3],explanation:"Both 'lucid' and 'pellucid' mean extremely clear and easy to understand. The clue 'even students with no background could follow' demands clarity. The other four options (abstruse, convoluted, esoteric, recondite) all mean difficult to understand.",difficulty:1,tags:["clarity"]},
  {id:"se2",sentence:"Despite the committee's efforts to reach a compromise, the negotiations remained _____, with neither side willing to make concessions.",choices:["productive","deadlocked","amicable","stalled","fruitful","harmonious"],correct:[1,3],explanation:"Both 'deadlocked' and 'stalled' mean stuck with no progress. The clue 'neither side willing to make concessions' signals an impasse. 'Productive,' 'fruitful,' 'amicable,' and 'harmonious' all suggest positive progress.",difficulty:1,tags:["conflict"]},
  {id:"se3",sentence:"The critic dismissed the novel as _____, arguing that its plot recycled tired conventions without adding anything original.",choices:["innovative","hackneyed","groundbreaking","derivative","provocative","seminal"],correct:[1,3],explanation:"Both 'hackneyed' and 'derivative' mean lacking originality, relying on borrowed or overused ideas. The clue 'recycled tired conventions without adding anything original' clearly points to unoriginality. The wrong answers all suggest freshness or significance.",difficulty:1,tags:["originality"]},
  {id:"se4",sentence:"The politician's _____ remarks about the opposition drew sharp criticism from commentators who expected a more measured tone from a senior statesman.",choices:["diplomatic","vitriolic","judicious","caustic","temperate","circumspect"],correct:[1,3],explanation:"Both 'vitriolic' and 'caustic' mean harshly critical or bitter. The clue 'drew sharp criticism' and the contrast with 'more measured tone' indicate that the remarks were excessively harsh. The other options (diplomatic, judicious, temperate, circumspect) all suggest restraint.",difficulty:2,tags:["speech"]},
  {id:"se5",sentence:"Once considered _____, the artist's work has recently been reevaluated and is now regarded as ahead of its time.",choices:["visionary","mediocre","prescient","unremarkable","pioneering","revolutionary"],correct:[1,3],explanation:"Both 'mediocre' and 'unremarkable' mean ordinary/not impressive. The 'once considered X, now regarded as ahead of its time' structure demands that X be negative — the old (wrong) view. The reevaluation changed the perception from dismissal to appreciation.",difficulty:2,tags:["reversal"]},
  {id:"se6",sentence:"The evidence against the defendant was entirely _____, based on speculation rather than verified facts.",choices:["substantiated","circumstantial","corroborated","conjectural","irrefutable","empirical"],correct:[1,3],explanation:"Both 'circumstantial' and 'conjectural' describe evidence that is indirect or based on guesswork rather than proof. The clue 'based on speculation rather than verified facts' confirms the evidence is not solid. 'Substantiated,' 'corroborated,' 'irrefutable,' and 'empirical' all suggest strong evidence.",difficulty:2,tags:["evidence"]},
  {id:"se7",sentence:"The CEO's management style was notably _____, granting department heads significant autonomy to make decisions without seeking approval.",choices:["autocratic","permissive","authoritarian","laissez-faire","dictatorial","rigid"],correct:[1,3],explanation:"Both 'permissive' and 'laissez-faire' describe a hands-off approach that allows freedom. The clue 'granting significant autonomy' and 'without seeking approval' confirm a relaxed management style. The wrong answers (autocratic, authoritarian, dictatorial, rigid) all describe controlling styles.",difficulty:2,tags:["leadership"]},
  {id:"se8",sentence:"The documentary presented a _____ portrait of the controversial figure, neither glorifying nor condemning his complex legacy.",choices:["biased","partisan","dispassionate","laudatory","impartial","critical"],correct:[2,4],explanation:"Both 'dispassionate' and 'impartial' mean unbiased and objective. The clue 'neither glorifying nor condemning' indicates balanced treatment. 'Biased' and 'partisan' suggest one-sidedness; 'laudatory' suggests praise; 'critical' suggests negativity.",difficulty:1,tags:["objectivity"]},
  {id:"se9",sentence:"The philosopher's argument, though _____ on the surface, contained a fundamental logical flaw that undermined its entire conclusion.",choices:["specious","implausible","cogent","fallacious","transparent","superficial"],correct:[0,3],explanation:"Both 'specious' and 'fallacious' mean seemingly correct but actually wrong. The key structure is 'though X on the surface, contained a flaw' — it looked good but was actually flawed. 'Cogent' means convincing (doesn't pair with a flaw). 'Implausible' means it doesn't look good (contradicts 'on the surface').",difficulty:3,tags:["logic"]},
  {id:"se10",sentence:"The governor's _____ response to the natural disaster was widely praised, as emergency services were deployed within hours of the event.",choices:["dilatory","prompt","sluggish","expeditious","belated","ineffectual"],correct:[1,3],explanation:"Both 'prompt' and 'expeditious' mean quick and efficient. The clue 'deployed within hours' and 'widely praised' confirm a fast response. 'Dilatory' (slow), 'sluggish,' 'belated' (late), and 'ineffectual' all describe poor responses.",difficulty:1,tags:["speed"]},
  {id:"se11",sentence:"The researcher's claims, though initially met with _____, were eventually validated by independent studies that replicated her findings.",choices:["acclaim","skepticism","enthusiasm","incredulity","support","indifference"],correct:[1,3],explanation:"Both 'skepticism' and 'incredulity' mean doubt or disbelief. The 'initially met with X, eventually validated' structure requires initial doubt. 'Acclaim,' 'enthusiasm,' and 'support' are positive initial reactions that don't create the needed contrast.",difficulty:1,tags:["reversal"]},
  {id:"se12",sentence:"The company's earnings report was deliberately _____, designed to present a rosier picture of financial health than the underlying data warranted.",choices:["candid","misleading","transparent","deceptive","forthright","accurate"],correct:[1,3],explanation:"Both 'misleading' and 'deceptive' mean intended to create a false impression. The clue 'deliberately' and 'rosier picture than warranted' confirm intentional misrepresentation. 'Candid,' 'transparent,' 'forthright,' and 'accurate' all suggest honesty.",difficulty:1,tags:["deception"]},
  {id:"se13",sentence:"The author's prose style is remarkably _____, conveying profound ideas in surprisingly few words.",choices:["verbose","prolix","economical","terse","ornate","embellished"],correct:[2,3],explanation:"Both 'economical' and 'terse' describe writing that uses few words effectively. The clue 'profound ideas in surprisingly few words' confirms brevity. 'Verbose,' 'prolix,' 'ornate,' and 'embellished' all describe wordy or elaborate writing.",difficulty:2,tags:["writing"]},
  {id:"se14",sentence:"Far from the _____ wilderness that early explorers had described, the region turned out to support a thriving and diverse ecosystem.",choices:["barren","lush","desolate","verdant","fertile","abundant"],correct:[0,2],explanation:"Both 'barren' and 'desolate' mean empty/lifeless. The 'far from X, turned out Y' structure means the reality contradicts the description. Early explorers said it was barren/desolate, but it was actually thriving. 'Lush,' 'verdant,' 'fertile,' and 'abundant' describe what it actually was, not what explorers described.",difficulty:2,tags:["contrast"]},
  {id:"se15",sentence:"The diplomat's _____ manner, which put even the most hostile negotiators at ease, was her greatest asset in high-stakes discussions.",choices:["brusque","genial","abrasive","affable","contentious","officious"],correct:[1,3],explanation:"Both 'genial' and 'affable' mean warm, friendly, and easy to talk to. The clue 'put even hostile negotiators at ease' demands a friendly manner. 'Brusque' (abrupt), 'abrasive' (harsh), 'contentious' (argumentative), and 'officious' (meddlesome) would not put anyone at ease.",difficulty:1,tags:["personality"]},
  {id:"se16",sentence:"The editorial board found the manuscript _____, lacking the rigor and originality necessary for publication in a peer-reviewed journal.",choices:["exemplary","wanting","superlative","deficient","commendable","meritorious"],correct:[1,3],explanation:"Both 'wanting' and 'deficient' mean lacking or falling short. The clue 'lacking the rigor and originality necessary' confirms the manuscript didn't meet standards. The other options (exemplary, superlative, commendable, meritorious) all indicate high quality.",difficulty:2,tags:["quality"]},
  {id:"se17",sentence:"The speaker's argument was undermined by its reliance on _____ evidence that could not withstand even cursory scrutiny.",choices:["robust","flimsy","compelling","tenuous","irrefutable","substantial"],correct:[1,3],explanation:"Both 'flimsy' and 'tenuous' mean weak and insubstantial. The clue 'undermined' and 'could not withstand even cursory scrutiny' confirm the evidence was weak. 'Robust,' 'compelling,' 'irrefutable,' and 'substantial' all describe strong evidence.",difficulty:1,tags:["evidence"]},
  {id:"se18",sentence:"The new regulations were designed to _____ the growing influence of monopolies in the technology sector.",choices:["bolster","curtail","augment","curb","amplify","enhance"],correct:[1,3],explanation:"Both 'curtail' and 'curb' mean to restrain or reduce. Regulations against monopolies would aim to limit their influence. 'Bolster,' 'augment,' 'amplify,' and 'enhance' all mean to increase or strengthen — the opposite of what anti-monopoly regulations do.",difficulty:1,tags:["regulation"]},
  {id:"se19",sentence:"The artist's latest exhibition was _____, featuring works that challenged viewers' expectations and defied easy categorization.",choices:["conventional","provocative","traditional","audacious","predictable","orthodox"],correct:[1,3],explanation:"Both 'provocative' and 'audacious' describe something bold and challenging. The clues 'challenged expectations' and 'defied easy categorization' point to boldness. 'Conventional,' 'traditional,' 'predictable,' and 'orthodox' all suggest the opposite — sticking to norms.",difficulty:2,tags:["art"]},
  {id:"se20",sentence:"The witness's testimony was _____, full of contradictions and inconsistencies that cast doubt on the reliability of her account.",choices:["cogent","coherent","muddled","compelling","garbled","persuasive"],correct:[2,4],explanation:"Both 'muddled' and 'garbled' mean confused and unclear. The clue 'full of contradictions and inconsistencies' confirms the testimony was disorganized. 'Cogent' (clear and logical), 'coherent' (logical), 'compelling' (convincing), and 'persuasive' all suggest clarity and reliability.",difficulty:2,tags:["testimony"]},
  {id:"se21",sentence:"The mayor's _____ spending on personal luxuries drew public outrage during a time of severe fiscal austerity.",choices:["frugal","lavish","prudent","profligate","restrained","moderate"],correct:[1,3],explanation:"Both 'lavish' and 'profligate' mean recklessly extravagant. Spending on personal luxuries during austerity would be wasteful and draw outrage. 'Frugal,' 'prudent,' 'restrained,' and 'moderate' all suggest careful spending.",difficulty:1,tags:["spending"]},
  {id:"se22",sentence:"The phenomenon, once thought to be _____, is now understood to be widespread, occurring in ecosystems around the globe.",choices:["ubiquitous","anomalous","pervasive","rare","commonplace","prevalent"],correct:[1,3],explanation:"Both 'anomalous' and 'rare' mean unusual/uncommon. The 'once thought X, now understood to be widespread' structure requires X to be the opposite of widespread. 'Ubiquitous,' 'pervasive,' 'commonplace,' and 'prevalent' all mean widespread — that's what it actually is, not what it was once thought to be.",difficulty:2,tags:["reversal"]},
  {id:"se23",sentence:"The orchestra's performance was technically _____, yet it lacked the emotional depth that distinguishes a competent rendition from a truly memorable one.",choices:["flawed","proficient","deficient","adept","amateurish","innovative"],correct:[1,3],explanation:"Both 'proficient' and 'adept' mean skilled and competent. The 'technically X yet lacked emotional depth' structure means the performance was skillful but uninspired. 'Flawed,' 'deficient,' and 'amateurish' suggest technical weakness, which contradicts 'technically.'",difficulty:2,tags:["contrast"]},
  {id:"se24",sentence:"The comedian's humor was so _____ that audience members often needed a moment to realize they had been insulted.",choices:["overt","subtle","blatant","understated","flagrant","conspicuous"],correct:[1,3],explanation:"Both 'subtle' and 'understated' mean not immediately obvious. If audience members 'needed a moment to realize,' the humor was not obvious — it was indirect and refined. 'Overt,' 'blatant,' 'flagrant,' and 'conspicuous' all mean obvious and impossible to miss.",difficulty:1,tags:["subtlety"]},
  {id:"se25",sentence:"The scientist's _____ approach to research, questioning every assumption and testing every variable, ultimately led to a breakthrough that others had overlooked.",choices:["cursory","meticulous","superficial","painstaking","hasty","negligent"],correct:[1,3],explanation:"Both 'meticulous' and 'painstaking' mean extremely careful and thorough. The clue 'questioning every assumption and testing every variable' describes thorough work. 'Cursory' (brief), 'superficial' (shallow), 'hasty' (rushed), and 'negligent' (careless) are all opposites.",difficulty:1,tags:["thoroughness"]}
];
